version: '3.4'

services:
  tinycrm.api-gateway:
    image: tinycrm.api-gateway
    ports:
      - "3000:80"
    build:
      context: .
      dockerfile: APIGateway/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - tinycrm.products.api
      - tinycrm.sales.api
    links:
      - tinycrm.products.api
      - tinycrm.sales.api
  tinycrm.products.api:
    image: tinycrm.products
    ports:
      - "5001:80"
    build:
      context: .
      dockerfile: Services/Products/Presentation/TinyCRM.Products.API/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
      - CONNECTION_STRING=Host=tinycrm.db; Port=5432; Database=TinyCRM.Products; Username=postgres; Password=password
      - RABBITMQ_HOST=tinycrm.rabbitmq
    depends_on:
      tinycrm.db:
        condition: service_healthy
      tinycrm.rabbitmq:
        condition: service_healthy
    links:
      - tinycrm.db
      - tinycrm.rabbitmq
  tinycrm.sales.api:
    image: tinycrm.sales
    ports:
      - "5002:80"
    build:
      context: .
      dockerfile: Services/Sales/Presentation/TinyCRM.Sales.API/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
      - CONNECTION_STRING=Host=tinycrm.db; Port=5432; Database=TinyCRM.Sales; Username=postgres; Password=password
      - RABBITMQ_HOST=tinycrm.rabbitmq
    depends_on:
      tinycrm.db:
        condition: service_healthy
      tinycrm.rabbitmq:
        condition: service_healthy
    links:
      - tinycrm.db
      - tinycrm.rabbitmq
  tinycrm.db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - crmdata:/var/opt/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  tinycrm.redis:
    image: redis
    ports:
      - "6379:6379"
  tinycrm.rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 30s
      retries: 3
volumes:
  crmdata: