version: '3.4'

services:
  tinycrm.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=yourStrong(!)Password
    ports:
      - "14433:1433"
    volumes:
      - crmdata:/var/opt/mssql
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools/bin/sqlcmd", "-Usa", "-PyourStrong(!)Password", "-Q", "select 1" ]
      interval: 1s
      retries: 20
  tinycrm.redis:
    image: redis
    ports:
      - "6379:6379"
volumes:
  crmdata:

