version: '3.4'

services:
  tinycrm.product.api:
    image: ${DOCKER_REGISTRY-}tinycrm.product.api
    ports:
      - "5001:443"
      - "5000:80"
    build:
      context: .
      dockerfile: Services/Product/Presentation/TinyCRM.ProductManagement.API/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
      - CONNECTION_STRING=Server=tinycrm.db;Database=TinyCRM.Product;UID=sa;Password=yourStrong(!)Password;TrustServerCertificate=True;
  tinycrm.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=yourStrong(!)Password
    ports:
      - "14433:1433"
    volumes:
      - crmdata:/var/opt/mssql
  tinycrm.redis:
    image: redis
    ports:
      - "6379:6379"
volumes:
  crmdata:

