version: '3.4'

services:
  tinycrm.db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - crmdata:/var/opt/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user" ]
      interval: 10s
      timeout: 5s
      retries: 5
  tinycrm.redis:
    image: redis
    ports:
      - "6379:6379"
volumes:
  crmdata:

